### ISSUE TITLE
need help composer error

### ISSUE THREAD

**Issue by MonMohon** [mohammad-fouladgar/laravel-mobile-verification#158]
![image](https://user-images.githubusercontent.com/304477/98320491-1986ef00-2009-11eb-9849-2fb2e0512dcf.png)

**Comment by mohammad-fouladgar** [comment]
@MonMohon Please check out this link:
https://stackoverflow.com/questions/36611550/how-to-resolve-a-can-only-install-one-of-conflict

**Comment by mohammad-fouladgar** [comment]
I'll close this issue. But you can re-open this if you need it.

**Comment by MonMohon** [comment]
i can't able to sort out the issue

installed package
laravel/framework v8.14.0
guzzlehttp/guzzle 7.2.0

error
Problem 1
    - Installation request for fouladgar/laravel-mobile-verification ^1.2 -> satisfiable by fouladgar/laravel-mobile-verification[v1.2.0].
    - Installation request for laravel/framework (locked at v8.14.0, required as ^8.12) -> satisfiable by laravel/framework[v8.14.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].

**Comment by MonMohon** [comment]
> @MonMohon, I'll close this issue. But you can re-open this if you need it.

bro need you help

**Comment by 50bhan** [comment]
@MonMohon Your problem is related to dependencies and not this package. So send your `composer.json` file and this way it's more likely to find a solution.

**Comment by MonMohon** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.1"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by mohammad-fouladgar** [comment]
@MonMohon  We are fixing this issue. And we will release a new version.

**Comment by mohammad-fouladgar** [comment]
@MonMohon  The version 2.0.0 was released. Please try to install again.

**Comment by MonMohon** [comment]
> @MonMohon The version 2.0.0 was released. Please try to install again.

thanks
