### ISSUE TITLE
Verified issue

### ISSUE THREAD

**Issue by arebuffo** [mohammad-fouladgar/laravel-mobile-verification#161]
Hi,

I managed to make it work, it works flawlessly, with my own VueJS SPA, sanctum as the auth, etc.

The only trouble I have is that once I verified the token, the user is not refreshed until the next login. Is this normal? I can't find a way to do it without forcing something.

Thank you

**Comment by 50bhan** [comment]
@arebuffo What do you mean by `the user is not refreshed until the next login`?

**Comment by arebuffo** [comment]
Hi,

Sorry about the bad phrasing.

When the user verifies the token successfully, the hasVerifiedMobile() still returns false, unless I logoff and logon again. The routes are still redirected to the verification page.

Alex

**Comment by arebuffo** [comment]
I think it might be my mistake. 
I replaced, for the sake of simplicity, the middleware route 'verified':

        'verified' => \App\Http\Middleware\EnsureMobileIsVerified::class,
//        'verified' => \App\Http\Middleware\EnsureEmailIsVerified::class,

and maybe I should include mobile.verified.

**Comment by mohammad-fouladgar** [comment]
@arebuffo Yes. You should not use it as a middleware globally.
Please read this part of the document :
https://github.com/mohammad-fouladgar/laravel-mobile-verification#protecting-routes

**Comment by mohammad-fouladgar** [comment]
You do not need to register `EnsureMobileIsVerified` middleware, because this has already registered. Also, This does not relate to `EnsureEmailIsVerified` middleware.

**Comment by mohammad-fouladgar** [comment]
I'll close this issue, but you can reopen if you need it.
