### ISSUE TITLE
Send SMS Manually

### ISSUE THREAD

**Issue by alr2413** [mohammad-fouladgar/laravel-mobile-verification#167]
Hi, 
Thanks for providing this package.
Can you provide a sample code about how to send a verification sms manually not only in case of user registration?
To make it clear, i wanna to send sms code notification on every user login attempt.

**Comment by mohammad-fouladgar** [comment]
Hi, you're welcome!
Do you mean OTP or re-send verification code to the logged-in user?

**Comment by alr2413** [comment]
hmmmm,

I need a custom event like `event(new Registered($user));` to trigger it whenever i want (sth like this `event(new SendMobileVerification($user))` would be nice). 
Also, i don't want to send the verification code right after user registration.
To clarify, consider a situation that you wanna send a verification code to a specific user from admin panel.

![Screen Shot 2021-06-23 at 10 33 23 PM](https://user-images.githubusercontent.com/10116275/123146429-15fa8800-d473-11eb-9c4d-7d67ba9c305b.png)

do you have any idea how to implement that?

**Comment by mohammad-fouladgar** [comment]
@alr2413
You can use `Fouladgar\MobileVerification\Tokens\TokenBroker` in a controller, and send a `user` instance of `Fouladgar\MobileVerification\Contracts\MustVerifyMobile` as the first argument to the `sendToken` method.

 But, this feature currently is not supported. Feel free to send a PR for it with the test.

**Comment by alr2413** [comment]
@mohammad-fouladgar.
Thanks, but how to use `TokenBroker` in my controller? it requires a token repository.
![Screen Shot 2021-06-29 at 10 57 37 AM](https://user-images.githubusercontent.com/10116275/123748147-10fd6480-d8c9-11eb-8b42-b6e08bf6b043.png)

**Comment by 50bhan** [comment]
@alr2413 If you don't care, you can just resolve the broker and that's it, the container will takes care of it.

**Comment by alr2413** [comment]
@50bhan 
how to resolve the broker? can you explain it more?

**Comment by 50bhan** [comment]
@alr2413 You can resolve any service  with its dependencies from the Laravel container:

`        $broker = resolve(TokenBroker::class);
`

**Comment by mohammad-fouladgar** [comment]
@alr2413  You can re-open this issue if you want.

**Comment by alr2413** [comment]
i tried, but it's not working. 
this is my code
```
$broker = resolve(TokenBroker::class);
$broker->sendToken($user);
```
it throws the following error:
```
ArgumentCountError
Too few arguments to function Fouladgar\MobileVerification\Tokens\TokenBroker::__construct(), 0 passed in
```

**Comment by 50bhan** [comment]
@alr2413 Honestly I can't reproduce your issue. When I try to resolve TokenBroker, I'll get it without any problem:

![Screen Shot 2021-07-16 at 11 58 36](https://user-images.githubusercontent.com/36772278/125909429-6602e8f8-0579-4ae3-a103-f9098aea0ebe.png)

@mohammad-fouladgar Any ideas?

**Comment by mohammad-fouladgar** [comment]
@50bhan I will try your approach. But it looks the correct way.

**Comment by mohammad-fouladgar** [comment]
@alr2413 Please try this way:

```php
// In the web.php file
use Fouladgar\MobileVerification\Tokens\TokenBrokerInterface;
use Illuminate\Support\Facades\Route;


Route::get('/mob', function (TokenBrokerInterface $broker) {
    dd($broker);
});

// OR this way

Route::get('/mob', function () {
    dd(resolve(TokenBrokerInterface::class));
});
```
It works correctly for me.

**Comment by alr2413** [comment]
ok, thanks.
i'll test it
