### ISSUE TITLE
Livewire Implementation

### ISSUE THREAD

**Issue by beneyraheem** [mohammad-fouladgar/laravel-mobile-verification#168]
This package has a good documentation with laravel implementation but I really want to change components to livewire. I can not find any easy way of doing that. 
Can someone please give me an idea about this?

**Comment by 50bhan** [comment]
@beneyraheem No experience with livewire. Ping @mohammad-fouladgar.

**Comment by mohammad-fouladgar** [comment]
@beneyraheem After installing Livewire create a page like below name **verify.blade.php**: 
```html
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @livewireStyles

    <title>Laravel Mobile Verification</title>
</head>
<body>
<div>
    <h1>Verify Mobile</h1>
    @livewire('verify-mobile')
</div>

@livewireScripts

</body>
</html>
```
Then make a component named `VerifyMobile`:
```sh
php artisan make:livewire VerifyMobile
```
Running this command will generate the following two files:
```php
// app/Http/Livewire/VerifyMobile.php
namespace App\Http\Livewire;

use Livewire\Component;

class VerifyMobile extends Component
{
    public function render()
    {
        return view('livewire.verify-mobile');
    }
}
// ----------------------------------------------------------------------
// resources/views/livewire/verify-mobile.blade.php
// Put this content in the verify-mobile.blade.php
<div>
    <h1>Verify Mobile:</h1>
    <form action="{{route('mobile.verify')}}" method="post">
        Please send token: <input type="text" name="token">
    </form>
</div>
```
Finally, load the page you included Livewire on in the browser:
For example:
```php
Route::get('/verify', function (){
    return view('verify');
})->middleware('auth');
```
That's it.

**Comment by beneyraheem** [comment]
Thank you @mohammad-fouladgar for the prompt answer. I think your method is exactly how it use in laravel blade components. 

Here is I have used it in the livewire. Can you please confirm, is it the right way?

Create a livewire component "VerifyMobile"
```
php artisan make:livewire VerifyMobile
```
Put this content in resources/views/livewire/verify-mobile.blade.php
```
<div>
    <form wire:submit.prevent="verify">
        <div>
              <input type="text" wire:model="code">
              <button type="submit">Verify</button>
        </div>
    </form>
</div>
```
In the app/Http/Livewire/VerifyMobile.php define the submit method and necessary fields
```
use Fouladgar\MobileVerification\Tokens\TokenBroker;
use Fouladgar\MobileVerification\Tokens\TokenRepositoryInterface;

    public $code;
    public $user;

    public function mount()
    {
        $this->user = User::findOrFail(Auth::id());
    }

    public function verify(TokenRepositoryInterface $tokenRepositoryInterface)
    {
        $tokenBroker = new TokenBroker($tokenRepositoryInterface);

        $tokenBroker->verifyToken($this->user, $this->code);
    }

    public function render()
    {
        return view('livewire.verify-mobile');
    }
```
Route
I can use extra middleware to protect this route.
```
use App\Http\Livewire\VerifyMobile;

Route::get('/mobile-verify', VerifyMobile::class);
```

I don't know if this is the right method to use from your package, but this works. Let me know your comments.

**Comment by mohammad-fouladgar** [comment]
@beneyraheem you don't need to use `TokenBroker`. Your route must be protected by auth middleware and your action form in verify-mobile component must use the verify.mobile route.

**Comment by beneyraheem** [comment]
@mohammad-fouladgar when we use the default form action livewire will reload the page. Thats not what I want. The whole point of livewire is to make an AJAX request to the server and updated data.

**Comment by mohammad-fouladgar** [comment]
Got it, let me try to Ajax request. Currently I have no idea. But your approach is a true way though.

**Comment by mohammad-fouladgar** [comment]
@beneyraheem Currently, we have to use this approach, but we should add support Livewire as soon as possible. 
Please try this way:
```html
{{--resources/views/livewire/verify-mobile.blade.php--}}
<div>
    @if (session()->has('invalidMessage'))
        <div class="alert alert-danger">
            {{ session('invalidMessage') }}
        </div>
    @endif

    @if (session()->has('mobileVerificationVerified'))
        <div class="alert alert-success">
            {{ session('mobileVerificationVerified') }}
        </div>
    @endif

    <form wire:submit.prevent="verify">
        <div>
            <input type="text" wire:model="code">
            <button type="submit">Verify</button>
        </div>
    </form>
</div>
```

```php
//app/Http/Livewire/VerifyMobile.php
<?php

namespace App\Http\Livewire;

use Fouladgar\MobileVerification\Contracts\MustVerifyMobile;
use Fouladgar\MobileVerification\Exceptions\InvalidTokenException;
use Fouladgar\MobileVerification\Tokens\TokenBrokerInterface;
use Livewire\Component;

class VerifyMobile extends Component
{
    public $code;

    public function render()
    {
        return view('livewire.verify-mobile');
    }

    public function verify(TokenBrokerInterface $tokenBroker)
    {
        /** @var MustVerifyMobile $user */
        $user = auth()->user();

        if ($user->hasVerifiedMobile()) {
            // put any logic here.
            return;
        }
        
        try {
            $tokenBroker->verifyToken($user, $this->code);
        } catch (InvalidTokenException $e) {
            session()->flash('invalidMessage',$e->getMessage());
            return ;
        }

        session()->flash('mobileVerificationVerified', __('MobileVerification::mobile_verifier.successful_verification'));
    }
}
```
You can check out this trait `Fouladgar\MobileVerification\Concerns\VerifiesMobiles` just to get how it works.

Also, please feel free to make a PR to add livewire support.

**Comment by jimiero** [comment]
@mohammad-fouladgar @beneyraheem 

any idea how i can use this package combined with this https://filamentphp.com/plugins/hasan-ahani-otp-input

that plugin has a 

->afterStateUpdated(function (string $state){
                })

But unfortunately seems I can't call me method 

public function verify(TokenRepositoryInterface $tokenRepositoryInterface)

Any idea ?

**Comment by mohammad-fouladgar** [comment]
> @mohammad-fouladgar @beneyraheem
> 
> any idea how i can use this package combined with this https://filamentphp.com/plugins/hasan-ahani-otp-input
> 
> that plugin has a
> 
> ->afterStateUpdated(function (string $state){ })
> 
> But unfortunately seems I can't call me method
> 
> public function verify(TokenRepositoryInterface $tokenRepositoryInterface)
> 
> Any idea ?

The above mentioned package is about OTP and our package is for verifing mobile number. If you are using OTP, you already have a verified mobile number. There is another package that provides an easier way to authenticate users by OTP: https://github.com/mohammad-fouladgar/laravel-otp
