### ISSUE TITLE
check when was the last code sent to current user

### ISSUE THREAD

**Issue by Shujee** [mohammad-fouladgar/laravel-mobile-verification#171]
Firstly, congrats on creating a functional and complete as well as generic-enough package. I was wondering if there is a way of checking when was the last time we sent code to a user? I'm using default settings of the package (cache driver, no `mobile_verification_tokens` `table).

**Comment by mohammad-fouladgar** [comment]
You're welcome😉, 
If you are using cache driver, you can't find the last sent at. But I try to find a way. I let you know as soon as possible.

**Comment by mohammad-fouladgar** [comment]
@Shujee There is no way to know when you sent the code to a user if you used the cache drive.
We can add this time while storing data in the cache. I think this way resolves this issue. I'll release a new version to add this new feature.

**Comment by mohammad-fouladgar** [comment]
@Shujee V2.7.0 has been released.  You either can write a custom controller and use the 'getLatestSentAt' method thankful of `TokenBroker` or resolve the `TokenBroker` and use this method everywhere that you want.

**Comment by Shujee** [comment]
Thanks a lot.
