### ISSUE TITLE
Base table or view already exists

### ISSUE THREAD

**Issue by AkikiCharbel** [mohammad-fouladgar/laravel-mobile-verification#178]
When I installed this plugin, there was an error with AddSentAtInTokensTable. We already have the table, we just need to update it.

Schema::create($this->tokenTable, function (Blueprint $table) {
$table->timestamp('sent_at')->nullable();
});

should be replaced by 

Schema::table($this->tokenTable, function (Blueprint $table) {
$table->timestamp('sent_at')->nullable();
});

**Comment by mohammad-fouladgar** [comment]
You can run this command for publishing the migration files:
`php artisan vendor:publish --provider="Fouladgar\MobileVerification\ServiceProvider" --tag="migrations"`
So, you can modify these files as you want.

**Comment by mohammad-fouladgar** [comment]
Dear @AkikiCharbel 
Because this issue seems to be inactive for quite some time now, I've closed this issue. Please feel free to reopen this if you need.
