### ISSUE TITLE
Ability to enable/disable or add custom event 

### ISSUE THREAD

**Issue by jimiero** [mohammad-fouladgar/laravel-mobile-verification#181]
Hello @mohammad-fouladgar ,

Currently the plugin sends the sms when the Registered::class is triggered,

Is it possible to disable this so I can decide when I want to send the sms instead?

**Comment by mohammad-fouladgar** [comment]
Currently, it is not possible.
But, it is possible not to dispatch the `event(new Registered($user));` event. 
You can use the `Fouladgar\MobileVerification\Tokens\TokenBroker` class to send and verify the user's mobile directly.
