### ISSUE TITLE
Unhandled match case 'backoff'

### ISSUE THREAD

**Issue by ibnIrshad** [mohammad-fouladgar/laravel-mobile-verification#182]
This error occurs at `SendMobileVerificationNotificationQueueable.php: 13` right after registering the user.

See full stack trace here. I have no idea what caused it as it was working fine before. Regardless it seems there should be a match handling case for the "backoff" case, whatever that means. I can't fix it myself because I don't know what the backoff case is supposed to do.

```php

class SendMobileVerificationNotificationQueueable extends AbstractMobileVerificationListener implements ShouldQueue
{
    public function __get(string $name): mixed
    {
        return match ($name) {
            'tries' => config('mobile_verifier.queue.tries'),
            'timeout' => config('mobile_verifier.queue.timeout'),
            'connection' => config('mobile_verifier.queue.connection'),
            'queue' => config('mobile_verifier.queue.queue'),
        };
    }
}
```

**Comment by mohammad-fouladgar** [comment]
Please explain more about your error.
I think you should check out your queue config.
