### ISSUE TITLE
[Feature] Custom Validation Messages

### ISSUE THREAD

**Issue by 50bhan** [mohammad-fouladgar/laravel-mobile-verification#25]
At the moment, all validation messages are set to defaults and user can't change them. So it would be nice to have an ability to customize them. Specially based on language! 

This led to more flexibility and less trouble for developers.

**Comment by mohammad-fouladgar** [comment]
@50bhan I think this issue will close with #165 PR, right?

**Comment by 50bhan** [comment]
@mohammad-fouladgar Yes, we can close this issue now.
