### ISSUE TITLE
Undefined property: Fouladgar\MobileVerification\Notifications\Messages\Payload::$getToken 

### ISSUE THREAD

**Issue by saeed7m** [mohammad-fouladgar/laravel-mobile-verification#28]
Can you please explain more about this?
where can i use this code ?which file ?
 
use Illuminate\Auth\Events\Registered;
// Register user
 event(new Registered($user));
//...

I have this error  and think that it may be related to this

Undefined property: Fouladgar\MobileVerification\Notifications\Messages\Payload::$getToken 

I'm new to laravel ,,, sorry

**Comment by mohammad-fouladgar** [comment]
@saeed7m 
It's error is correct ! Because the `Payload` class doesn't have `getToken` property. This class has a `getToken()` function(method). Check **[doc](https://github.com/mohammad-fouladgar/laravel-mobile-verification#sms-client)** again please.

Fix it in your 'SMS-client' implemented as following: 
```php
// YourSmsClient class

 public function sendMessage(Payload $payload)
 {
     return $this->smsService->send($payload->getTo(), $payload->getToken());
 }
```

**Comment by saeed7m** [comment]
here is my function and my sms -client .
could you please check ? 


public function sendMessage(Payload $payload)
    {
           $curl = curl_init();
            curl_setopt_array($curl, 
            array(
            CURLOPT_URL => "http://*******/send/verify",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => "type=1&param1=**$payload->getToken()**&receptor=**$payload->getTo()**&template=test",
            CURLOPT_HTTPHEADER => array(
            "apikey:",
            "cache-control: no-cache",
            "content-type: application/x-www-form-urlencoded",
            ),
            )); 
            $response = curl_exec($curl);
            $err = curl_error($curl);
            curl_close($curl);
    }

**Comment by mohammad-fouladgar** [comment]
@saeed7m 
Try this:
```php
CURLOPT_POSTFIELDS => "type=1&param1=". $payload->getToken(). "&receptor=".$payload->getTo()."&template=test",
```

**Comment by saeed7m** [comment]
Great , 
waiting  for more perfect package ....
thank u
