### ISSUE TITLE
 syntax error, unexpected 'verify' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 

### ISSUE THREAD

**Issue by saeed7m** [mohammad-fouladgar/laravel-mobile-verification#29]
using laravel     7.5.2
and php      7.2.29

::Composer\Autoload\includeFile
D:\*******\vendor\fouladgar\laravel-mobile-verification\src\Http\Controllers\MobileVerificationController.php:25
    /*
    |--------------------------------------------------------------------------
    | Mobile Verification Controller
    | This controller is responsible for handling mobile verification for any
    | user that recently registered with the application. Tokens may also
    | be re-sent if the user didn't receive the original token message.

    protected $redirectTo = '/home';
    public verify()
{
....... verify code ( check database ...
}

**Comment by mohammad-fouladgar** [comment]
@saeed7m 
I didn't understand anything. Can you explain more?
When do you encounter with this error exactly?
What is this!!!?
> {
....... verify code ( check database ...
}

**Comment by saeed7m** [comment]
The sms is sent correctly
And since I don't use ajax (because I don't know how) so I made a VIew that takes the code and calls the verify controller but I get this error

 **syntax error, unexpected 'verify' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)** 

inside verify  i'm set the time of verify and verify the user in final step !

**Comment by mohammad-fouladgar** [comment]
In this `MobileVerificationController` not exists `public verify()`.  Did you add it manually ?

**Comment by saeed7m** [comment]
sure. default MobileVerificationController  has public verify() . i just want add my code inside . 

but i have :
syntax error, unexpected 'verify' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

**Comment by mohammad-fouladgar** [comment]
@saeed7m 
Did you read this section of **[document](https://github.com/mohammad-fouladgar/laravel-mobile-verification#customize-routes-and-controller)** for customizing controller?

**Comment by saeed7m** [comment]
first ì try customize controller ... i have error . next i used default controller without any changes . again i have syntax error .

**Comment by mohammad-fouladgar** [comment]
You should customize your controller as below:
```php
<?php

namespace App\Http\Controllers;

use Fouladgar\MobileVerification\Http\Controllers\BaseVerificationController;
use Fouladgar\MobileVerification\Http\Requests\VerificationRequest;
use Illuminate\Http\Request;

class MobileVerificationController extends BaseVerificationController
{
    /**
     * Where to redirect users after verification.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    public function verify(VerificationRequest $request)
    {
       //  Put your code here...
    }

   public function resend(Request $request)
   {
     // Put your code here...
   }
}
```
 And set your controller namespace in config file.
