### ISSUE TITLE
Fix RedirectUsers trait for Laravel 7

### ISSUE THREAD

**Issue by mohammad-fouladgar** [mohammad-fouladgar/laravel-mobile-verification#30]
Hi @50bhan I hope you're doing great as usual. 
Can you fix this issue please?

**Comment by 50bhan** [comment]
@mohammad-fouladgar Hey buddy. Thanks a lot. 

Sure, I will fix it and add an explanation here :+1:

**Comment by 50bhan** [comment]
Due to moving Laravel UI stuff in a separate package, we had to add RedirectUsers trait to project to avoid break down on Laravel 7.

**Comment by mohammad-fouladgar** [comment]
Thanks. Good job ✌🏻
