### ISSUE TITLE
custom redirect for resend and verify

### ISSUE THREAD

**Issue by saeed7m** [mohammad-fouladgar/laravel-mobile-verification#32]
How can I differentiate between **verify** and **resend**    **redirect To**   ? for example after verified mobile redirect to home and after resend stay on verify form to get new code ?

**Comment by 50bhan** [comment]
@saeed7m At this moment we don't have this feature. But I try to implement it in my spare time.

**Comment by mohammad-fouladgar** [comment]
@saeed7m @50bhan 
In my point of view, we don't need to that. Now, after re-sending token, user will be redirected to the back URL (previous page) to enter the token.Isn't that so?

**Comment by 50bhan** [comment]
@mohammad-fouladgar Yes, if this is all we want (Stay on send token page and redirect to somewhere else), we don't need this. But we can't custom this in other scenarios.

**Comment by mohammad-fouladgar** [comment]
@50bhan 
What other scenarios? After requesting re-sending of the token, the user waits to receive the new token and then enter it. I cannot think of another scenario :thinking:  
Can you explain with a example to me ?

**Comment by mohammad-fouladgar** [comment]
I will close this issue, but you can open it if needed.
